# -*- coding: utf-8 -*-
"""Web Scrapping from Amazone Reviews of Apple Iphone 12 Mini Using BeautifulSoup.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zo-o_TJGvLRODJun-4MozceKQMK0GUHL
"""

!pip install requests beautifulsoup4

from bs4 import BeautifulSoup as bs
import requests

link = "https://www.amazon.in/New-Apple-iPhone-Mini-128GB/product-reviews/B08L5VN68Y/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"

page = requests.get(link)
page

page.content

soup = bs(page.content,'html.parser')
soup

print(soup.prettify())

names = soup.find_all('span',class_ = "a-profile-name")
names

# Can remove repeatations in name cz of prioritizing the comments
name=[]
for i in names:
  if i not in name:
    name.append(i)
name

customer_name = []
for i in range(len(name)):
  customer_name.append(name[i].get_text())
customer_name

customer_name.pop(1)

len(customer_name)

Rating = soup.find_all('i',{"data-hook":"review-star-rating"})
Rating

Ratings = []
for i in range(len(Rating)):
  Ratings.append(Rating[i].get_text())
Ratings

Review = soup.find_all("span", {"data-hook":"review-body"})
Review

Reviews = []
for i in range(len(Review)):
  Reviews.append(Review[i].get_text())
Reviews

Reviews[:] = [i.rstrip('\n') for i in Reviews]
Reviews[:] = [i.lstrip('\n') for i in Reviews]
Reviews

len(Reviews)

customer_name
Ratings
Review

import pandas as pd

df = pd.DataFrame()
df['Customer Name'] = customer_name
df['Rating'] = Ratings
df['Reviews'] =Reviews
df

df.to_csv('amazon.csv')